services:
  - type: worker
    name: celery-worker
    region: ohio
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A app.celery_app worker --loglevel=info -Q lumenary_composite_queue,lumenary_campaign_queue,lumenary_pipeline_queue,lumenary_call_queue --concurrency=4 --prefetch-multiplier=1"
    autoDeploy: false
    envVars:
      - key: CELERY_BROKER_URL
        value: "amqp://guest:guest@localhost:5672//"
  - type: web
    name: app
    region: ohio
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app"
    autoDeploy: false
    envVars:
      - key: CELERY_BROKER_URL
        value: "amqp://guest:guest@localhost:5672//"
  - type: web
    name: flower
    region: ohio
    plan: free
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery flower --app tasks --loglevel info"
    autoDeploy: false
    envVars:
      - key: CELERY_BROKER_URL
        value: "amqp://guest:guest@localhost:5672//"
  - type: redis
    name: celery-redis
    region: ohio
    plan: starter # we choose a plan with persistence to ensure tasks are not lost upon restart
    maxmemoryPolicy: noeviction # recommended policy for queues
    ipAllowList: [] # only allow internal connections
